### ISSUE TITLE
Error: Unable to sign-in.

### ISSUE THREAD

**Issue by nerd190** [seanbreckenridge/oh-my-stars#1]
Hi! thank you for `mystars`! It used to work for me but some time has past since I last installed this and after getting new devices and re-installing, I can no longer sign-in, I tried both ways, via the command prompt and via `.netrc` too.
 Errors:
```python
~ ❯ mystars
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mystars", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/core.py", line 177, in main
    search_result = db.all_repos()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/db.py", line 90, in all_repos
    all_items = self._db.table().search(lambda _: True)
TypeError: table() missing 1 required positional argument: 'name'

~ ❯ mystars -u
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mystars", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/core.py", line 122, in main
    names = set([r['full_name'] for r in db.all_repos()])
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/db.py", line 90, in all_repos
    all_items = self._db.table().search(lambda _: True)
TypeError: table() missing 1 required positional argument: 'name'

~ ❯ mystars -r
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mystars", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/core.py", line 105, in main
    with StarredDB(MY_STARS_HOME, mode) as db:
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/db.py", line 23, in __init__
    self._db.purge_tables()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge_tables'
```

**Comment by purarue** [comment]
Hey, sorry I forgot to enable notifications on the repo after enabling issues here so I didn't see this.

I've since fixed the breaking API changes from the tinydb and github3 (dependencies) major version upgrades, could you re-install and see if it works for you now?

`pip install --upgrade 'git+https://github.com/seanbreckenridge/oh-my-stars'` should do

**Comment by nerd190** [comment]
Hi! thank you for trying to fix this!
I used the above command to update but still get an error so tried uninstall/re-install, still the same error.
Note: This time around, it no longer prompts you to sign in when `.netrc` is absent, like it used to.
I then used `.netrc` instead, but the same error occurs, just in case it was an invalid token, to test things out, I made a new one allowing everything available, still the same error.
I then tried the same but on another device but no luck still.
This is the error I recieve each time:
```bash
$ mystars
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mystars", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/core.py", line 177, in main
    search_result = db.all_repos()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/db.py", line 90, in all_repos
    all_items = self._db.table().search(lambda _: True)
TypeError: table() missing 1 required positional argument: 'name'
```
Thanks again, its appreciated.

**Comment by purarue** [comment]
Hmm weird, that still looks like the old code. I thought doing a `pip install --upgrade` would have worked. May have something to do with this being a pip install from a git directory.

Compare:

https://github.com/seanbreckenridge/oh-my-stars/blob/master/ohmystars/db.py#L90

`all_items = self._db.table('_default').search(lambda _: True)`

To your error:

```
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ohmystars/db.py", line 90, in all_repos
    all_items = self._db.table().search(lambda _: True)
```

I had that same error yesterday debugging, which is why I added the `'_default'`

Perhaps try something like:

```bash
$ pip uninstall -y oh-my-stars
# make sure its actually gone
$ pip list | grep 'oh-my-stars'
$ which mystars # should fail, else delete the executable as well
$ pip install --no-cache-dir 'git+https://github.com/seanbreckenridge/oh-my-stars'
```

**Comment by purarue** [comment]
Also, just as an FYI, I'm somewhat unhappy with how this is working currently

I don't particularly understand tinydb (what this uses to store information) and havent put in the time to learn it properly, so I've just sort of been hacking on this. Is now at the point where stuff isn't working perfectly, so I typically just end up doing `mystars -r` in the background every few hours, which isn't ideal.

I'll probably at some point remove the indexing of my own repos, and move the db code closer back to the original, so there are less bugs.

The output format would still remain the same, that was the initial reason I forked this.

**Comment by purarue** [comment]
While were discussing here, as long as the other issue is resolved, I just pushed those updates; removed some of the complexities with it indexing my own repos/having to check against your github login

https://github.com/seanbreckenridge/oh-my-stars/commit/df659ca885de654a4730c714512eba17e4531cf1

Assuming the above worked to uninstall/reinstall, should be able to do the same again

let me know if you have any issues with that

**Comment by nerd190** [comment]
**THANK YOU!** `pip install --no-cache-dir` did it, must've been pip caching the older pkg still,
Glad to have this back again!
As your last comment, I have no knowledge of tinydb either, as long as the repos remain grep'able I'm happy!, `sqlite3` is pretty straight forward, but perhaps instead of a database, a lighter/simpler way would be to `curl` Github API's json then query it with `jq`, I do the same already to check-download-log-query new github releases. Then again, I suppose this would be alot slower, especially if you had thousands of stars.

Closing this issue as its fixed! thank you again!
